---
name: Nextcloud - MariaDB - Docs - Firefox
author: Didi Hoffmann <didi@green-coding.io>
description: Es wird ein weiterer Nutzer erstellt. Danach wird ein leeres Markdown Dokument erstellt und mit diesem Nutzer geteilt. Beide Nutzer greifen dann simultan auf das Dokument zu und editieren es kollaborativ. Jeder Nutzer fügt abwechselnd 50 Zeichen zu dem Dokument hinzu und es wird geguckt, dass dies auch bei den anderen Nutzern ankommt. Die Eingabe wird pro Zeichen mit 200ms delay simuliert.
compose-file: !include compose-mariadb.yml

sci:
  R_d: collaborative edit

services:
  gcb-playwright:
    image: greencoding/gcb_playwright:v14
    depends_on:
      nc:
        condition: service_healthy
    volumes:
       - /tmp/.X11-unix:/tmp/.X11-unix # for debugging in non-headless mode
    environment:
       DISPLAY: ":0" # for debugging in non-headless mode
    log-stderr: true
    log-stdout: true
  db:
    log-stderr: true
    log-stdout: true
  nc:
    log-stderr: true
    log-stdout: true
  ncs:
    log-stderr: true
    log-stdout: true

flow:
  - name: Install Nextcloud
    container: gcb-playwright
    commands:
      - type: console
        command: python3 /tmp/repo/nextcloud_install.py firefox
        note: Installing Nextcloud
        read-notes-stdout: true
        log-stdout: true
        log-stderr: true
  - name: Create User
    container: gcb-playwright
    commands:
      - type: console
        command: python3 /tmp/repo/nextcloud_docs_create_user.py firefox
        note: Create user
        read-notes-stdout: true
        log-stdout: true
        log-stderr: true
  - name: Create doc and share
    container: gcb-playwright
    commands:
      - type: console
        command: python3 /tmp/repo/nextcloud_docs_create_doc_and_share.py firefox
        note: Create document and share
        read-notes-stdout: true
        log-stdout: true
        log-stderr: true
  - name: Collaborate
    container: gcb-playwright
    commands:
      - type: console
        command: python3 /tmp/repo/nextcloud_docs_collaboration.py firefox
        note: dev
        read-notes-stdout: true
        read-sci-stdout: true
        log-stdout: true
        log-stderr: true
  - name: Delete user and doc
    container: gcb-playwright
    commands:
      - type: console
        command: python3 /tmp/repo/nextcloud_docs_delete_user_and_doc.py firefox
        note: dev
        read-notes-stdout: true
        read-sci-stdout: true
        log-stdout: true
        log-stderr: true

