---
name: Nextcloud - MariaDB - Calendar - Firefox
author: Didi Hoffmann <didi@green-coding.io>
description: Nextcloud login über das Web Interface. Erstellen eines neuen Kalender-Eintrag. Ändern des Kalender Eintrag. Löschen des Kalender Eintrag.
compose-file: !include compose-mariadb.yml

services:
  gcb-playwright:
    image: greencoding/gcb_playwright:v14
    depends_on:
      nc:
        condition: service_healthy
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # for debugging in non-headless mode
    environment:
       DISPLAY: ":0" # for debugging in non-headless mode


flow:
  - name: Calendar
    container: gcb-playwright
    commands:
      - type: console
        command: python3 /tmp/repo/nextcloud_calendar.py firefox
        note: Creating event
        read-notes-stdout: true
        read-sci-stdout: true
        log-stdout: true
        log-stderr: true
