---
name: Nextcloud - MariaDB - Files - Chromium
author: Didi Hoffmann <didi@green-coding.io>
description: Nextcloud login über das Web Interface. Erstellen einer neuen Datei. Erstellen eines Sharing Link für die Datei mit 1 MB. Teilen der Datei und Download mit einem anderen Browser.
compose-file: !include compose-mariadb.yml

services:
  gcb-playwright:
    image: greencoding/gcb_playwright:v14
    depends_on:
      nc:
        condition: service_healthy
    volumes:
      - /run/user/1000/wayland-0:/run/user/1000/wayland-0 # for debugging in non-headless mode
    environment:
       DISPLAY: ":0" # for debugging in non-headless mode
       XDG_RUNTIME_DIR: "/run/user/1000"

flow:
  - name: File Sharing
    container: gcb-playwright
    commands:
      - type: console
        command: python3 /tmp/repo/nextcloud_files.py chromium
        note: Creating event
        read-notes-stdout: true
        read-sci-stdout: true
        log-stdout: true
        log-stderr: true
