---
name: Nextcloud - MariaDB - Install - Firefox
author: Arne Tarara <arne@green-coding.io>
description: Installieren des offiziellen Nextcloud Docker containers mit MariaDB Datenbank. Dann booten und 1 Std. Idle.
compose-file: !include compose-mariadb.yml

services:
  gcb-playwright:
    image: greencoding/gcb_playwright:v14
    depends_on:
      nc:
        condition: service_healthy
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # for debugging in non-headless mode
    environment:
       DISPLAY: ":0" # for debugging in non-headless mode


flow:
  - name: Install Nextcloud
    container: gcb-playwright
    commands:
      - type: console
        command: python3 /tmp/repo/nextcloud_install.py firefox
        read-notes-stdout: true
        log-stdout: true
        log-stderr: true

  - name: Idle for 3600
    container: gcb-playwright
    commands:
      - type: console
        command: sleep 3600
        read-notes-stdout: true
        log-stdout: true
        log-stderr: true
