---
name: Nextcloud - MariaDB - Video - Firefox
author: Didi Hoffmann <didi@green-coding.io>
description: Video-Konferenz mit Nextcloud Talk app. Zuerst wird ein Call von einem Browser gestartet und ein Sharing-Link erstellt. Danach kommen zwei Teilnehmer in den Anruf. Die Videokonferenz wird via Firefox mit einem Farbwechsel-Demo-Video und einem Rauschen als Audio simuliert.
compose-file: !include compose-mariadb.yml

services:
  gcb-playwright:
    image: greencoding/gcb_playwright:v14
    depends_on:
      nc:
        condition: service_healthy
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # for debugging in non-headless mode
    environment:
       DISPLAY: ":0" # for debugging in non-headless mode


flow:
  - name: Video Conference
    container: gcb-playwright
    commands:
      - type: console
        command: python3 /tmp/repo/nextcloud_video.py firefox
        read-notes-stdout: true
        log-stdout: true
        log-stderr: true
